/**
 * Tests: JWT Token Utility (src/utils/jwt.ts)
 *
 * WHY this matters for assessment:
 *   JWT tokens are the authentication backbone.  These tests prove:
 *   1. Tokens contain the expected claims (id, role).
 *   2. Tokens signed with our secret can be verified.
 *   3. Tampered or invalid tokens are rejected.
 *   4. Expired tokens are rejected — critical for session security.
 *
 * The JWT_SECRET is set in setup.ts before this module is imported,
 * so process.env.JWT_SECRET is always defined during these tests.
 */

import jwt from "jsonwebtoken";
import { generateToken, verifyToken } from "../../utils/jwt";

const TEST_SECRET = "test-super-secret-key-for-jest"; // mirrors setup.ts

describe("generateToken", () => {
  it("should return a valid JWT string", () => {
    const token = generateToken({ id: "user-123", role: "ENGINEER" });

    // A JWT is three base64url segments separated by dots
    expect(typeof token).toBe("string");
    expect(token.split(".")).toHaveLength(3);
  });

  it("should embed the provided payload claims inside the token", () => {
    const payload = { id: "user-abc", role: "ADMIN" };
    const token = generateToken(payload);

    // Decode without verifying to inspect claims
    const decoded = jwt.decode(token) as Record<string, unknown>;

    expect(decoded.id).toBe("user-abc");
    expect(decoded.role).toBe("ADMIN");
  });

  it("should set the token to expire in 1 day", () => {
    const before = Math.floor(Date.now() / 1000);
    const token = generateToken({ id: "x" });
    const decoded = jwt.decode(token) as Record<string, number>;

    // exp (expiry) should be roughly 24 h ahead of now
    const oneDaySeconds = 24 * 60 * 60;
    expect(decoded.exp).toBeGreaterThanOrEqual(before + oneDaySeconds - 5);
    expect(decoded.exp).toBeLessThanOrEqual(before + oneDaySeconds + 5);
  });
});

describe("verifyToken", () => {
  it("should successfully decode a token generated by generateToken", () => {
    const token = generateToken({ id: "user-123", role: "VIEWER" });
    const decoded = verifyToken(token) as Record<string, unknown>;

    expect(decoded.id).toBe("user-123");
    expect(decoded.role).toBe("VIEWER");
  });

  it("should throw JsonWebTokenError for a tampered token", () => {
    const token = generateToken({ id: "user-123" });
    // Flip one character in the signature segment to simulate tampering
    const parts = token.split(".");
    parts[2] = parts[2].slice(0, -1) + (parts[2].endsWith("a") ? "b" : "a");
    const tampered = parts.join(".");

    expect(() => verifyToken(tampered)).toThrow();
  });

  it("should throw for a token signed with a different secret", () => {
    const foreignToken = jwt.sign({ id: "hacker" }, "wrong-secret");
    expect(() => verifyToken(foreignToken)).toThrow();
  });

  it("should throw TokenExpiredError for an already-expired token", () => {
    // Sign a token that expired 1 second in the past
    const expiredToken = jwt.sign(
      { id: "user-123" },
      TEST_SECRET,
      { expiresIn: -1 } // negative = immediately expired
    );

    expect(() => verifyToken(expiredToken)).toThrow(/expired/i);
  });
});
